### ISSUE TITLE
Search in all articles

### ISSUE THREAD

**Issue by 22u2** [owncloud/news#185]
It would be great to have a search in all articles by title or contains maybe.

**Comment by mcmurphyrp** [comment]
Hi all, a search on all articles would be highly appreciated. IMO its a must have for a news app, considering you have plenty of feeds and want to search specific terms etc. 

I would be happy to contribute to get a search implemented into the app.

**Comment by kgraefe** [comment]
Is the need for a separate search bar still valid since ownCloud 8 changed the search bar at the top to be app-specific?

**Comment by Raydiation** [comment]
@kgraefe did not know of that change, can you link me something? But apparently it does not load anything which means it should be possible to reuse the top search. This will simplify things.

**Comment by kgraefe** [comment]
https://owncloud.org/blog/owncloud-server-8-0-for-users/ (paragraph "Improved search")

**Comment by Raydiation** [comment]
In general we want full text search on the database level. Since we store HTML markup in the database (item's body field) we need to get rid of it and keep it in a separate column. We can also append the title and link to the text, so we need to create a duplicate column where we can run the search queries on. @fossxplorer is gonna hate me xD

These columns need to be created properly, otherwise you'll only be able to search in new entries. For bigger systems this can take hours, so this migration will be optional. We are going to need to do the following:

* [ ] Create a migration command, e.g.: php -f console.php news:create_serach_index that goes through all the previous entries with an empty column and creates an index.
* [ ] The index field's content is created like this: 

    ```php
    $index = strtolower(strip_tags($body) . ' ' . strip_tags($title) . ' ' . $link)
    ```
* [ ] The controller method that returns the items is going to take another parameter called search. That parameter is, when passed to the database layer turned into an SQL command, e.g.: ?**search=test%20string** will be turned into 

    ```sql
    WHERE searchindex LIKE '%test%' AND searchindex LIKE '%string%'
    ```
 We need to take care of proper escaping.

* [ ] Clientside the search term will be reflected in the URL, e.g. **#/items/?search=test%20string**. That way we can do a simple route redirect and refresh the content area. The input field will have a 300-500ms delay to not reload to often

**Comment by Raydiation** [comment]
Work on this will be done in the next branch which aims for 8.1 

I cant guarantee however that this is finished when 8.1 is released.

**Comment by Raydiation** [comment]
Linking this for future use http://stackoverflow.com/questions/5265288/update-command-line-output-i-e-for-progress

**Comment by Raydiation** [comment]
Clientside search is implemented in the next branch, all that is left is the migration for older articles and some testing :)

**Comment by jancborchardt** [comment]
@Raydiation btw – you can use the header search field for this. In Files, apps mgmt etc we moved to use the filed for in-app search. :)
