### ISSUE TITLE
Don't delete starred items when their feeds are deleted

### ISSUE THREAD

**Issue by IBBoard** [owncloud/news#490]
1. Sometimes I have feeds that I want to read and keep items from for reference. 
 2. Sometimes I have feeds that I want to keep items from for reference *and* I want to star them because they're particularly interesting and will be frequently used.
 3. Sometimes I have feeds that I read once and delete (web comics, etc).

I can do this with Thunderbird and it'll keep my history for as long as I don't delete stuff. In OC News my options appear to be: 
 * Increase the max count so that they don't get purged (prevents use case 3)
 * Star items I want to keep so that the purge (hopefully) doesn't remove them (prevents use case 2)
 * Star items I want to star and mark as unread the items that I want to keep (makes it hard to see what is really new vs just being kept, plus News's default behaviour is to mark as read on scrolling, plus I'd have to mark as unread each time I re-read it, plus I don't know whether it'd get purged anyway)

It'd be useful to have a specific "delete item" button for each feed item so that we can delete posts we've read and don't care about any more.

**Comment by BernhardPosselt** [comment]
Cleaning up issues right now and I'd like to consolidate this issue :)

To reiterate:
* Starring articles works more like a read later mechanic ATM
* Starred articles could be updated with bogus content (because every article is updated if newer information comes in), making it unfit for archiving
* Many feed readers use some sort of archive functionality to cover this use case

Archiving stuff from the web however has it's own complexities which could make up an entire app. This app is very different from a fast paced info-in info-out news reader. Therefore an app that does archiving well would be better suited for that task. Such an app could be the bookmarks app or maybe a separate pockit like app.

Like you pointed out there's a difference between a read later and archiving functionality. If you see the starring like a read later mechanism it's probably completely fine to delete the contents if the feed is deleted. If for whatever edge case reason this is not fine, you can still export and re-import the starred articles after re-adding the feed (or undo the deletion if it was an accident).

As a conclusion I'm consolidating this issue in #892 whose proposed fix is documented in the wiki: https://github.com/owncloud/news/wiki/bookmarks-plugin

If you want to work on this, feel free to ask for help!
