### ISSUE TITLE
Add keyboard shortcut for "Mark all as read"

### ISSUE THREAD

**Issue by gwvr** [owncloud/news#635]
Hi, hopefully this feature enhancement request is self explanatory..

I'd like to be able to mark all articles as read using a keyboard shortcut. This was possible with Google Reader and is possible with Feedly (with shift-a). I think this function is usually context sensitive, so all articles in the current view (feed/tag/global) are marked as read.

I've had a poke around the code, but wouldn't know what to add to js/gui/KeyboardShortcuts.js, or even if there is a function to hook the shortcut to. Sorry..

For info/comparison: other keyboard shortcuts used by Feedly are listed at http://feedly.uservoice.com/knowledgebase/articles/272051-keyboard-shortcuts
I am not suggesting that Owncloud News should use the same shortcuts as Feedly.

**Comment by oparoz** [comment]
@Raydiation - Backport request ;)

**Comment by Raydiation** [comment]
I don't do back ports ;) there's also no branch to back port things to

**Comment by oparoz** [comment]
I've noticed ;( and I think it's a problem with ownCloud apps in general.
As soon as we're close to a new major release, support for the current version stop which means having months to wait to have access to bug fixes, because we need to wait for a .2 or 3 release before being able to migrate.

**Comment by Raydiation** [comment]
We can talk about supporting older owncloud versions once I'm being paid for it ;D

**Comment by oparoz** [comment]
Why not do the opposite? Support the current version and rebase the dev branch?

**Comment by Raydiation** [comment]
This is already done in that way. The dev branch is merged into master once the first beta of the next release comes out

**Comment by Raydiation** [comment]
Also the problem that you address is probably not related to dev branches but to not having stableX branches

**Comment by oparoz** [comment]
Yes, stable branches would be nice, but you wouldn't have time to maintain them and that's a common problem among devs.
The merge from dev to master is done too early, because it effectively halts development of the app for the most stable version of oC for several months.
Users are stuck with 5.2.8 until probably August.

**Comment by Raydiation** [comment]
No, they are stuck for exactly one month until the beta hits stable https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by Raydiation** [comment]
That is of course only if they use they are using the master branch.

**Comment by oparoz** [comment]
Yes, but nobody upgrades until things stabilise.

**Comment by Raydiation** [comment]
So when is ownCloud stable? 8.1.0 which gets released as stable? Or 8.1.1, 8.1.2, 8.1.3, ...

For me if 8.1 hits 8.1.0 it's considered stable and my own instance is upgraded. Everything else is support for older versions which is no option for me unless working full time on it.

**Comment by Raydiation** [comment]
Another thing: backwards compatibility is not dropped intentionally, it is usually due to bug fixes which can not be backported to older versions or require special workarounds (e.g. CSP bugs for the 8.1 version). So depending on how easy it is to fix the current issues, the News app will still be compatible with older versions.

**Comment by oparoz** [comment]
It's difficult to pinpoint. It's when major issues discovered by early adopters have been ironed out. It usually takes a couple of dot releases before it happens. I'm sure the management team has a version they use to start building the EE version. They don't use the .0 release. So that should be the point at which oC is deemed stable enough to use in production and when apps should start supporting that branch only.
Of course, it might not always be possible to wait. The jump between 7 and 8 regarding the AppFramework was large and it was best to quickly abandon 7.

**Comment by Raydiation** [comment]
All in all this is a time problem. So if no one steps in to backport and maintain stuff for older versions this won't happen.

**Comment by gwvr** [comment]
So 8.1.0 is stable, but hasn't been released.. that seems a little confused.
It'd be helpful if the latest version of the app that supports the current "stable released release of Owncloud" (currently 5.2.8 for oc 8.0.x) were tagged as such.
I don't mind patiently waiting and updating both Owncloud and the News app every three months or so - it's less work for me!

**Comment by oparoz** [comment]
I was about to say. It's mainly a resources issue, I just wished it was possible to keep master compatible with what's most stable and just apply the necessary patches to the dev version to get it to work on the next release, until it becomes stable enough to get your full attention, but you probably won't find this satisfactory since you switch as soon as the .0 version is available and yo're the one doing all the work.

**Comment by Raydiation** [comment]
@gwvr no, 8.1.0 has not been released yet, but when it's released it will be tagged as stable.

In addition consider the 5.3.x releases to be pre-releases for 8.1 to iron out bugs both in core and the News app.
