### ISSUE TITLE
Feed updates of bigger installations

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/news#706]
The update process for an instance with > 10000 feed ids is extremely slow even when using 4 thread. How does your threading work?  Does each thread start at the lowest feed id?

I see a lots of following query in the DB:
Query   | 249  | Copying to tmp table | SELECT `feeds`.*, COUNT(`items`.`id`) AS `unread_count` FROM `oc_news_feeds` `feeds` LEFT OUTER JOIN `oc_news_folders` `folders` ON `feeds`.`folder_id` = `folders`.`id` LEFT JOIN `oc_news_items` `items` ON `feeds`.`id` = `items`.`feed_id` AND (`items`.`status` & 2) = 2 WHERE (`feeds`.`folder_id` = 0 OR `folders`.`deleted_at` = 0)AND `feeds`.`deleted_at` = 0 GROUP BY `feeds`.`id`, `feeds`.`user_id`, `feeds`.`url_hash`,`feeds`.`url`, `feeds`.`title`, `feeds`.`link`,`feeds`.`favicon_link`, `feeds`.`added`, `feeds`.`articles_per_update`, `feeds`.`folder_id`, `feeds`.`prevent_update`, `feeds`.`deleted_at` | 0.000    |

It looks like it's running the cleanup on very update, but isn't it wiser to, say, run the cleanup on every 5th run to reduce the initial update process?
This will also help a lot in case an update process is interrupted for some reason. Currently, it will start all over again and i have to wait hours just for the clean process of > 10000 feed ids.
I did hack your updater.py to achieve something similar a while back, but it was very ugly, but worked for my purpose.

Also, could the update be more efficient by for instance using the threads to update different feed ids? E.g with 4 threads, count(feeds)/4 and each thread will work with updating within their range.
Or is something similar currently implemented for the feed updater?

I'm working on an instance where the table oc_news_items alone is ~ 50GiB in size.

@Raydiation what do you think?

**Comment by Raydiation** [comment]
Bigger installations have different needs, that's why the update API exists (https://github.com/owncloud/news/wiki/Cron-1.2). You can very easily write your own updater to adapt it to your needs. 

The current process works in the following way: 
* Delete old feeds and folders
* Update all feeds of all users
* Delete old articles

That means that after updating all 100000 feeds the cleanup is run. Updating the 100k feeds should take way longer than the feed cleanup so this should actually not be an issue and come very close to your use case. You can read the source here (the join loop https://github.com/owncloud/news/blob/master/bin/updater/owncloud_news_updater/updater.py#L69 is blocking until everything finished): https://github.com/owncloud/news/blob/master/bin/updater/owncloud_news_updater/updater.py#L44

> Also, could the update be more efficient by for instance using the threads to update different feed ids? E.g with 4 threads, count(feeds)/4 and each thread will work with updating within their range.

Thats how it works ;)
