### ISSUE TITLE
[Feature request]  limit amount of feeds based on group

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/news#708]
For bigger installation, it would be very useful to be able to limit the max amount of feeds one user can have based user's group. We can set the values in config and grab it from there. E.g
'news_limit_feeds' => ("staff" => 100, "students" =>10)

@Raydiation

**Comment by Raydiation** [comment]
The basic issue here is that big installations may be overwhelmed with a lot of data, e.g. 50GB mysql tables with news item entries. 

Limitting the feeds will not actually work since news feeds from inactive users (e.g. user adds 10 feeds, never looks at the app again) will be fetched and will add up further data in the database. Even though this might be limitted to 10 feeds it will add massive amounts of data to your database.

So the solution to this problem is most likely to automatically delete feeds of inactive users. This can be done by writing a small like https://github.com/fossxplorer/inactiveapps which records when a user accessed an app. You can then get the users which havent used the news app in, lets say 2 months, and delete all their items and feeds from the database.

**Comment by Raydiation** [comment]
That is of course under the assumption that you are using the enable app for group feature already built into owncloud to limit usage to a known group of people and that active users actually read their feeds. In that case there should only be a limited volume of data since old read articles are deleted through the updater.

Don't forget to notify your users of the policy change BTW. If nothing helps you should limit the group of people that are able to access the news app BTW, maybe an opt in system where users have to request to be included in a group. And ofc you can always throw more hardware at it, like setting up db replication

**Comment by fossxplorer** [comment]
Thx a billion @Raydiation for this!
