### ISSUE TITLE
Keyboard arrow shortcut doesn't always work as expected

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/news#745]
When I read news I use the RIGHT arrow to jump to the next article. But sometime (around 1/10) the RIGHT arrow stop working. I must use the DOWN arrow once to make the RIGHT arrow working again...

I'm under news 5.2.7.

Btw, I really love this app! I use it every day!

**Comment by Raydiation** [comment]
Can not reproduce. The only thing that I've noticed from time to time is that it does not fully scroll to the item (some pixels left off) because it rerenders some things after the jump happens. I can't really control the rendering and I dont really care, I just hit right twice then. 

What you could do is find out if there are JS errors (hit f12 and go to the console). If there are errors that are reproducible I can start working on this. Otherwise this will be just a dead issue with no one being able to work on it because we dont know how to reproduce it. 

If you find out anything new please comment, maybe it is enough to reopen the issue ;)

**Comment by thenamelessthing** [comment]
I will look this if I found anything in the console.  Thanks you.

**Comment by thenamelessthing** [comment]
I don't kow if it's correct, but this is a printscreen with the js console open.

http://screencloud.net/v/qWx5

**Comment by thenamelessthing** [comment]
another: http://screencloud.net/v/lvqU

feed: http://fr.canoe.ca/rss/feed/nouvelles/sports.xml

**Comment by Raydiation** [comment]
Some browser extension is causing these errors but they should not actually impact the app. Can you s still try to turn them off?
