### ISSUE TITLE
Clicking on an item does not select it as "current item"

### ISSUE THREAD

**Issue by kgraefe** [owncloud/news#760]
I mainly use the compact view. When I click an item that is not the "current item" it expands so that I can read its content. If I want to read more I typically press 'o' to open it. But instead of the article I just read the app opens the last "current item". The same applies for other shortcuts, i.e. "next item".

**Comment by Raydiation** [comment]
Usually you are using keyboard shortcuts or the mouse so I dont see a reason to make it work together. In addition this behavior will introduce very complicated edge cases and probably confuse people a lot, like what happens if you scroll the last item out of the view and click next? Or if you are scrolling down and hit e for expanding the item? It will push the stuff up and worse, if you are in compact mode, it will mark things as read as they are pushed up. 

As for opening an article: If you are using the mouse you can use the earth icon. If you scroll down so that the earth icon is not in view, hitting o will still work.

**Comment by kgraefe** [comment]
The situation it bugs me most is when I scroll through the list of stared items (which has some videos to watch later) on my TV using a remote with a crippled mouse. It is easy to hit the headline of an article but hard to hit the earth icon. (And it is more annoying to press 'next item' through all the items than just scroll and click.)

**Comment by Raydiation** [comment]
Page down?
