### ISSUE TITLE
complain http:// feeds

### ISSUE THREAD

**Issue by sedrubal** [owncloud/news#761]
Do you want to implement something like a warning, if someone adds a feed through `http` instead of 
`https`? Or maybe you want automatically trying to fetch feeds through https...

**Comment by Raydiation** [comment]
By default if you leave out the protocol it will assume https, e.g. if you enter slashdot.org it will try to add the feed https://slashdot.org. If you add a feed using http you'll very likely want the http version, so it does not make sense to display a warning. 

Automatically trying to fetch feeds through https has various problems:
* If the feed fails to fetch over https, you need to fall back to http so theres no security benefit since an attacker can always force a fallback
* An additional check for https adds a lot of latency to the feed update which makes it very slow.

**Comment by sedrubal** [comment]
thanks.

But if you copy and paste the URL from the URL bar of Firefox, there always will be a `http://`. I think a small javascript toast: `! this link is http, do you want to try to fetch the feed through https?` popping out on adding the feed would be very nice...
