### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by baracoder** [owncloud/news#768]
I would like to hide or mark articles as read automatically based on title/description containing or not containing certain text.

**Comment by Raydiation** [comment]
Can you explain the usecase a bit better?

**Comment by Raydiation** [comment]
This sounds like a fully fledged rule engine like filters in thunderbird and requires a lot of time and effort to get it right and probably snowballs a huge bunch of enhancement/bugfix requests. You not only need a fully fledged user interface with various drop downs but also needs to be error checked aka duplicates, names etc. Its also much like a flexible programming language, aka if feed x contains y and z then do a, otherwise do b.

As outlined above this is a lot of work, so I want to understand the actual problem. Maybe we can avoid all this work, as in my opinion such a rule engine is a power user feature which applies to 0.1% of the userbase and offers a small return compared to the implementation and maintenance cost. Is this just a single feed that misbehaves and could be fixed on a feed library basis? 

ATM I'm leaning towards no.

**Comment by cosenal** [comment]
And any implementation (even a perfect one) would be prone to error. We really don't want the reader to mark articles as read by mistake.

**Comment by baracoder** [comment]
For example I have this feed http://www.hetzner-status.de/de.atom which contains a lot of entries which do not interest me. So i would like to filter out all entries which contain "Datenbank" or "Webhosting". 

Another way would be to use an external service like yahoo pipes to preprocess the feed http://pipes.yahoo.com/pipes/

**Comment by Raydiation** [comment]
Yep, using an external service like the one you've linked or creating a separate project for this seems like the way to go. You don't want the to be marked read, you want them to be ignored entirely. This should happen on the feed library level or using a proxy

**Comment by Raydiation** [comment]
Another thing would be to ask hetzner if they can provide extra filter parameters for the atom feed, like ?exclude=database,hosting

**Comment by sedrubal** [comment]
I can und er stand your doubt but I'd like this feature too. Using an external service makes owncloud news superfluous and using a proprietary service (e.g. yahoo pipes) gives yahoo the power of cencoring.

Here is a [PHP RSS filtering project](https://github.com/bionoren/rssFilter) which might be useful for implementing this feature.

**Comment by BernhardPosselt** [comment]
@sedrubal great link. Rather than integrating it (it is already a standalone client) we may want to create documentation and quick steps how to use it :)

We should add a Guide section in the wiki https://github.com/owncloud/news/wiki

@sedrubal can you take care of how of writing a step by step guide how to ingegrate this with ownCloud and why you want to use it?

**Comment by sedrubal** [comment]
Unfortunately I don't know this project. I only found it while searching for filtering RSS. Do you think, one can use this in combination with owncloud news?

**Comment by BernhardPosselt** [comment]
Yes, try it out and please report back if it worked. I've opened a security issue btw which I hope will get resolved quickly https://github.com/bionoren/rssFilter/issues/4

**Comment by sedrubal** [comment]
Can't make it run, see bionoren/rssFilter#5
