### ISSUE TITLE
»Refresh« button misbehaviours

### ISSUE THREAD

**Issue by cosenal** [owncloud/news#770]
Small things about the refresh button that make the ux annoying (probably easy to fix): 

- when I use the wheel to scroll, the button is there forever, but I want to make it disappear by, say, clicking on the body of an article, or by timeout.
- once you make the button appear with the keyboard and you go down again, you can't refresh using k anymore
- in fact, that button should appear only when there are new articles (js already checks for that in order to increment the counters in the feed list).

All of this is in non-compact view, but probably applies in compact view too.

[To be edited with more details].

cc @jancborchardt

**Comment by Raydiation** [comment]
in fact, that button should appear only when there are new articles (js already checks for that in order to increment the counters in the feed list).

I often use it to just get rid of read articles, also this might make it hard to discover this feature and there might be new articles which arent yet synced to the client and will be synced on refresh.

    when I use the wheel to scroll, the button is there forever, but I want to make it disappear by, say, clicking on the body of an article, or by timeout.

That will push up articles and probably mark them read if you use read on scroll, I also dont see a real point in hiding it 

No 2 is a valid problem :)
