### ISSUE TITLE
Editing feed name reorders while typing

### ISSUE THREAD

**Issue by tgrosinger** [owncloud/news#790]
When editing the name of a feed if you change the first letter the feed will be reordered while typing. This has unexpected results and interrupts the renaming. Feed should be reordered once the check button is clicked rather than while typing.

**ownCloud version**: 8.0.3
**News version**: 5.2.8
**Browser and version**: Firefox 37.0.1
**PHP version**: 

```
$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Distribution**:

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by Raydiation** [comment]
Oh, wow, you're good at finding this little quirks.

This is happening because of angular's two way binding, solution is probably using https://docs.angularjs.org/api/ng/directive/ngModelOptions here https://github.com/owncloud/news/blob/master/templates/part.navigation.feed.php#L59. I'm off over the weekend til Wednesday, if anyone wants to take a look and provide a PR, feel free to do so :)

**Comment by Raydiation** [comment]
nvm  was really easy :)

**Comment by tgrosinger** [comment]
Awesome, thank you!
