### ISSUE TITLE
Scroller for feed should be for the actual length of the content

### ISSUE THREAD

**Issue by oparoz** [owncloud/news#795]
### Env
8.0, news 5.2.8
Browser in portrait mode

### Steps to reproduce
1. Click on a feed
2. Scroll down

### Expected result
The bottom of the feed should be at the bottom of the page

### Actual result
There is en empty page after the end of the feed, filled with a gradient

**Comment by Raydiation** [comment]
This was done to let you scroll past the last entry to be able to mark the article read

**Comment by oparoz** [comment]
Yep, I figured out the reason, but it's bad UX imho. You need a button or a menu (on top of the shortcut which is already implemented in 5.3) to let users quickly mark all articles as read without having to scroll all that way. It's even more painful in compact mode.

**Comment by Raydiation** [comment]
First off keyboard shortcuts should be optional, so you can't argue for removing a mouse feature because there is a keyboard shortcut. Second it's not bad UX, there's no real drawback in fact there are  even advantages such as the above mentioned behavior and it lets you rest your eyes at the same position while scrolling at the bottom of the article. Sry, I don't see the issue.

**Comment by oparoz** [comment]
I'm arguing that there should be a quicker and less painful way to mark a feed as read. The shortcut is already there, the mouse "gesture" can stay, but an alternative is still needed imo.
I think you don't see the problem because you haven't tried to mark a feed as read when in portrait mode. It takes a lot of scrolling.
Another scenario is to want to read a few articles of a feed which has a lot of them. With a button, you're done very quickly, with the mouse, you have a lot of scrolling to do
