### ISSUE TITLE
View/modify feed sources

### ISSUE THREAD

**Issue by patricktokeeffe** [owncloud/news#798]
Yesterday I stopped retrieving new content in my Android client for (only) one of my podcasts. I've logged in to my owncloud instance and the feed is still there but refreshing does not pull in new content. I'm fairly sure it's actually the feed source but I can't view the uri associated with the feed, so I can't be 100% sure.

I'd love to be able to view and modify the source uri for feeds.

**Comment by cosenal** [comment]
Editing/viewing of feed xmlUrl was already discarded in other issues, see #117, #186 

I am suggesting two workarounds: instead of editing, you can remove and re-add the feed. For viewing the xmlUrl, you can export the list of feeds, along with xmlUrls from Settings->Subscriptions (OPML). Export and then ctrl+f :)

**Comment by patricktokeeffe** [comment]
Thanks. Prohibiting editing makes sense.
