### ISSUE TITLE
Self-signed certificate support?

### ISSUE THREAD

**Issue by ghostofkendo** [owncloud/news#814]
Hello,

I tried adding the RSS feed of a blog served over HTTPS with a self-signed certificate and I get the following error: "SSL Certificate is invalid"
Is there a way to add a security exception à la Firefox?

I am using ownCloud 8.0.4 and news 5.2.8.

**Comment by Raydiation** [comment]
Hi, :)

The solution for this issue is to add the custom certificate to your trusted server certificates. If you are in control of said website you can also use CSR on startssl.com to sign your certificate using a trusted authority for free.

Since this question resurfaces every once in a while, I'll add the preferred solution to the README

**Comment by ghostofkendo** [comment]
My bad. I searched for previous issues regarding this subject but, inadvertently, only among open issues.

Good idea to include this in the README though ;-)

**Comment by Raydiation** [comment]
https://github.com/owncloud/news#reading-feeds-that-use-self-signed-certificates
