### ISSUE TITLE
Cron not installed

### ISSUE THREAD

**Issue by martynvs** [owncloud/news#828]
I'm using the ownCloud plugin (version 8.1.0 (stable)) on FreeNAS 9.3 with the addon News 5.3.8. Everything works fine, except cron updating. According to the 'Cron' section in the admin page, it updates frequently and successfully, however, my News feeds aren't updated. When I look at my ownCloud log, it says: "Fatal: cron Not installed".
I posted this issue in the FreeNAS forum (https://forums.freenas.org/index.php?threads/owncloud-plugin-cron-not-installed.35519/), but they think cron is working fine and suggested I post an issue on this github.

What do you suggest I do to solve this issue?

**Comment by Raydiation** [comment]
How did you set up the owncloud cron?

**Comment by FiSh-MoB** [comment]
i got the same problem.
since i updated yesterday to 8.1.0 and updated news to 5.3.8 webcron wont update anymore.
in oc_jobs it says the last run was on timestamp "1437588901". (this was the last cron on 8.0.4 and news 5.2.8 - before i updated)
i installed the owncloud on my webspace manually. i moved the old files to another folder and uploaded the whole new content to the old folder. after that i uploaded the news 5.3.8 and copied my data folder and my config from 8.0.4 back into the right folder. upgrade process started and all worked, but news wont update with my webcron anymore.
i use wget to realise the job: "wget -O ~/htdocs/wget.txt https://sub.domain.tld/cron.php".

owncloud administration says, the last cron was done 9 minutes before, so that seems to be fine.

any suggestions?

**Comment by Raydiation** [comment]
@FiSh-MoB data/owncloud.log after the cron call please.

**Comment by FiSh-MoB** [comment]
config falue "define('DEBUG',true);" and Loglevel "all" in administrationarea, i get nothing in that log file. 
i will take have a look into that file in about 22 hours and edit my post, hopefully with something usefull.

**Comment by Raydiation** [comment]
Also please follow this guide https://github.com/owncloud/news#feeds-are-not-updated

**Comment by FiSh-MoB** [comment]
i did a temporary fix for myself, by changing the code of cron.php (line 146 to 150) from:
```javascript
			$job = $jobList->getNext();
			if ($job != null) {
				$job->execute($jobList, $logger);
				$jobList->setLastJob($job);
			}
```
to
```javascript
			$jobs = $jobList->getAll();
			foreach ($jobs as $job) {
				$job->execute($jobList, $logger);
			}
```
so every webcron all jobs get updated and not only one.

**Comment by Raydiation** [comment]
@FiSh-MoB i see

I will put webcron on the list of cron versions that dont work in conjuction with the News app. The issue here is the same as with the webinterface namely php timeouts. The ajax cron has an additional downside of stalling web interface load.

I think the way to go is system cron and python updater only.

**Comment by xn--nding-jua** [comment]
Hey,

I can confirm @FiSh-MoB 's workaround. The news-app is working with webcron then. The ownCloud-core issue can be found here: https://github.com/owncloud/core/issues/8531

kind regards,
Chris
