### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mat-mo** [owncloud/news#845]
Hello,

I would like to request Right-to-Left support for the news app.
Here is a screenshot from the news app with wrong RTL
![wrong rtl](https://cloud.githubusercontent.com/assets/4245366/9461978/1f1514d8-4b1b-11e5-80da-07e7316e5cbc.png)
VS. correct RTL from other RSS app with RTL support 
![correct rtl](https://cloud.githubusercontent.com/assets/4245366/9461980/2128c4ae-4b1b-11e5-8a99-769b7b1f0e18.png)

**Comment by Raydiation** [comment]
CSS file to make changes: https://github.com/owncloud/news/blob/master/css/content.css

Changes will need to be uglified with grunt. To do that change into the js/ folder and run

sudo npm -g install grunt-cli
npm install

To build the CSS run

grunt

or to build when you change the file:

grunt watch

**Comment by Raydiation** [comment]
Can you post a link to an example feed?

**Comment by mat-mo** [comment]
https://feeds2.feedburner.com/newsgeekfeed

**Comment by Raydiation** [comment]
I've researched some things and it's tricker than I thought. Currently all style attributes are stripped out because it's a possible XSS vector (you can put JavaScript into CSS ;D), so the style="direction: rtl" which is on a few tags (not all!) won't work. 

Then there's the HTML dir attribute (http://www.w3.org/International/questions/qa-html-dir) which is not used in your case, but that won't work because it's currently stripped out (we use 2 whitelist sanitizers)

The only real option I see here is to switch everything in a feed to RTL if it matches a specified language, which would ofc suck if your feed also serves english. Long term goal would be to submit patches upstream for picoFeed to add the dir attribute.

**Comment by mat-mo** [comment]
This is interesting, The correct scrrenshot comes from miniflux (https://github.com/miniflux/miniflux) which was written by the person who wrote picofeed for it (it is @fguillot) so picofeed does support it, unless it is done in a higher level than the feed handler.

**Comment by Raydiation** [comment]
@fguillot @mkresin anything special in miniflux that deals with RTL?

**Comment by mkresin** [comment]
Miniflux evaluates the language property if the item. If it's a RTL language, ```dir="rtl"``` will be added to the div which contains the content. Picofeed already provides the necessary helper function ```PicoFeed\Parser\Parser::isLanguageRTL($item['language'])```.

The item language property will contain the language of the feed item if provided, otherwise the language of the feed is used.

Furthermore, we allow the user to manually flag a feed as RTL, for cases where neither the feed, nor item indicate which language is used. As last effort, the user can (temporary) toggle the text direction of an item using a keyboard shortcut.

**Comment by Raydiation** [comment]
Thanks! First fix should be straight forward then :)

**Comment by Raydiation** [comment]
Ok, just pushed a fix but I can't read this :dancer: 

@mat-mo can you use the latest master version and check if it works? You need to readd the feed for it to work

**Comment by mat-mo** [comment]
Thanks! i can't use latest on my Prod machine, and testing machine i can pull it to and look at it?

**Comment by Raydiation** [comment]
You can download it directly from github, just remember to rename the folder (remove the version), there's a download zip button on the right column of the main page

**Comment by mat-mo** [comment]
Thanks! works excellent for text area. it is not fixed for the title though.

On a side note, apart from directionality which is fixed by this patch, the alignment is still wrong. i.e the article is left aligned. see screenshot, it should be on the right, but that is probably harder to fix. 

![2015-08-30 12-50-30](https://cloud.githubusercontent.com/assets/4245366/9566661/edf7728e-4f15-11e5-90d6-fb4253d09c7f.png)

**Comment by Raydiation** [comment]
Isn't the article right aligned?

**Comment by mat-mo** [comment]
It is, and thanks for that. I was pointing out it should be on the far right, and not in the center of the page (left if we don't have the sidebar)

**Comment by Raydiation** [comment]
Ideally everything would be on the right (including the navigation). Mixing RTL and ltr  feeds would be very weird though since it would flip around when switching to an RTL feed. We need to keep consistency.

In short: I will fix the alignment and reading direction but won't move or change the layout. Think about the current design as being centered ;)

**Comment by Raydiation** [comment]
I will fix the title though however :).

BTW: is the the navigation entry spelled out correctly?

**Comment by mat-mo** [comment]
Fair enough, when I can read, i care less about the navigation menu (and more so as i use the keyboard anyway). the navigation entry is spelled correctly. 

Fun read in your spare time: 
https://upload.wikimedia.org/wikipedia/commons/c/cd/TwistedRoadToRTLSupport_Wikimania2015.pdf

**Comment by Raydiation** [comment]
Thanks :)

Yep, the numbers stuff is kinda brain fuck. My biggest issue however is that I can't read Hebrew so I have no idea what I'm doing xD
