### ISSUE TITLE
Updated articles are not shown

### ISSUE THREAD

**Issue by VynceCook** [owncloud/news#877]
Updated articles are not shown in the feeds.
I really miss the feature to see updated articles as new in the feeds.
In TT-Rss there is an option to mark updated articles as not read for a given feed.

**Comment by BernhardPosselt** [comment]
See https://github.com/fguillot/picoFeed/issues/95

All in all very complicated issue since a lot of feeds misbehave, e.g. youtube updates the feed when a new comment is added.

Suggestions welcome.

**Comment by VynceCook** [comment]
Ideally, it would be a parameter to set for each feed. The user can decide if he wants the updated articles or not. It also might be an option to add to star articles.
I agree that it cannot be generalised to all feeds, but it is very important for some feeds.
We may miss important things without this feature.

**Comment by BernhardPosselt** [comment]
@IBBoard @cwmke @kgraefe @ogasser @vgezer  @cosenal @MorrisJobke @LukasReschke your opinions on this?

I know that we tried to add a lot of options/settings per feed and it seems its the only way to fix this is indeed to add a custom "receive updates" settings which is on by default. 

Solution as far as I can see is to compare pubdates and update the items if it changed.

**Comment by cwmke** [comment]
I think you're right.  Publish date comparisons seem like the logical way to go about it.  I can see why someone might like the ability to disable the option globally and enable it for a specific feed, or enable it globally and disable specific feeds.  Personally, I don't re-read articles so I would not use the option but I think it is something useful to add for others.

**Comment by VynceCook** [comment]
Indeed. I will be very useful (to me). For now, I must poll each article (which I want to know new updates) every day by hand, which is very painful.

**Comment by IBBoard** [comment]
I had occasionally wondered what happens if someone updates a post - how many RSS feeds update correctly and how many feed readers will notify users of the update?

Depending on what content changes, then YouTube might be correct (e.g. if it includes the comment count in the text then technically the post has been updated each time).

In terms of a coding solution then I think using the pubdate is the best option, and treat "no pub date" as a value of 0 - if people can't put a pub date on then you can't work out whether it is newer. As you put in your picoFeed comment then hashing the title and content as well would be more accurate, but might have a bit of an overhead (although MD5 is "good enough" for these purposes in that it'll have a low enough likelihood of accidental collisions - is it really that slow to MD5 the content of a post compared to, say, the time taken to insert into the database?)

Maybe trust the pub/modified date if specified and hash it and treat it as an update if the content changes if there's no pub/modified date?

**Comment by BernhardPosselt** [comment]
Please test if it works properly in master :)

**Comment by cwmke** [comment]
Will there be an option for disabling this somewhere in the future?  So far it appears to work pretty well from what I've seen but I prefer to not have updated articles show again.  Thanks for any thoughts.

**Comment by BernhardPosselt** [comment]
I'm not marking the article as unread so I doubt that we need an option to disable it for now

**Comment by IBBoard** [comment]
Personally, I think the "marking as unread" is the most useful bit - I hide read messages, so I'll never see updated posts unless they become unread again!

That said, I can see that we don't want that functionality without the ability to disable the update, because YouTube feeds and the like would be a pain.

**Comment by VynceCook** [comment]
Thank you for the feature. I modified a little the patch to set as unread if the article is a starred one. Now if I am interested in having article updates, I just have to set it as a starred article.

**Comment by IBBoard** [comment]
That's an idea - maybe we need a three-way setting? "Don't mark as unread if updated", "Mark as unread if updated" and "Mark as unread if starred".

**Comment by BernhardPosselt** [comment]
My goal is too have as few settings as possible. We should go for the most sane setting as default and then only if it is absolutely necessary add additional settings to override the behavior.

The reason for this is that each setting adds test and implementation complexity, is hard to communicate in short way (what icon do we use?) and is nearly impossible to "take away" from the user even if it did not make sense (check out the nautilus discussion xD) 

I think we can let it auto update without changing the read status for every feed. The question is if and when we should mark it unread.

**Comment by BernhardPosselt** [comment]
Another thing: At some point we probably want to port the app to angular 2. The more settings and exceptions we create, the more work to port it will be.

**Comment by VynceCook** [comment]
I understand that always mark as unread may be very painful for some feeds. But it is very useful in order to not miss updated articles. Mark as unread if the article is starred seems a good compromise.

**Comment by BernhardPosselt** [comment]
@VynceCook that will be horrible for youtube videos ;)

**Comment by VynceCook** [comment]
Oups, I forgot people who starred youtube videos! But Without adding a new setting or category, it will be difficult to have a rule which fit all needs :-/

**Comment by BernhardPosselt** [comment]
Probably a setting per feed that enables marking unread would be the best solution

**Comment by BernhardPosselt** [comment]
"opt in unread"

**Comment by VynceCook** [comment]
tt-rss works that way.  It works well.

**Comment by IBBoard** [comment]
I think the problem here is that there is no "sane" behaviour. Updating without marking as unread (or otherwise indicating that it updated in a way that the user might notice) is probably pointless for 99% of users - yes, they'll always have the latest version, but they'll never know about it. Updating and marking as unread has issues with feeds like YouTube that include constantly changing content and (correctly) keep updating their "modified" date (admittedly they should probably *not* include that content, but that's a different argument).

As for "too many settings", I think we're looking at one setting, it's just that it is a setting that isn't boolean. And thinking about it, it might need four possible values:
 * Never (For feeds that give good content at first, then change it at a later date - do you want to be silently breaking previously good feeds where ownCloud News effectively cached the good copy?)
 * Update but don't mark as unread (For people who only have a few items in their feeds, they re-read them occasionally and the feed regularly updates articles)
 * Update starred items and mark as unread (For people who want to selectively see updates on the specific articles that interest them)
 * Update items and mark as unread (For people who have quiet feeds and don't want to miss any updates)

As for porting to Angular 2 - I don't know enough to care either way. I'm too "old school". The last patch I did was a pain in the backside. I made some small changes to CSS and suddently I was installing a dozen libraries from the system repos and downloading half of the Internet to install another dozen libraries from non-system repos just to make the CSS change *actually* apply!

**Comment by BernhardPosselt** [comment]
@IBBoard ;D yep thats how javascript works: no proper standard library, everything is in a separate library. This is done for CSS minification btw ;)

 The goal should probably be to cover 80-99% of all usecases so I guess opt-in mark unread will work for this. If @IBBoard points prove to be a serious issue we can take a look at them later on.

@VynceCook can you open a new issue?

**Comment by IBBoard** [comment]
Just as long as the setting doesn't start with a boolean, then, so that it *can* be extended in future ;)

**Comment by VynceCook** [comment]
@BernhardPosselt I just opened a new issue
