### ISSUE TITLE
Question: Why is Webcron a problem?

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/news#881]
Hi,
can you please explain me, why using webcron causes issues using the News App?
What's the difference if the File is called from internal php or triggered via wget?

**Comment by BernhardPosselt** [comment]
It's a core implementation issue: basically both web and ajax cron have a timeout since they are triggered by a web request. So it was (imho correctly) decided to keep the jobs as short as possible.

This is done by keeping all jobs in a queue and only running one job per call. This in turn means that the feed update cron job will not be run every time you run your cron so feeds are not updated in a timely manner.

**Comment by BernhardPosselt** [comment]
TL;DR: cron executes all jobs, web + ajax execute only one job

**Comment by stefan-niedermann** [comment]
hm, okay, thanks for your explenation. though its said because many share hosters don't provide access to system cron, so it would be really really nice if webcron could work, too... :disappointed:

**Comment by BernhardPosselt** [comment]
Use the custom updater then ;)

**Comment by BernhardPosselt** [comment]
You can run the updater from any server.
