### ISSUE TITLE
Middle and right mouse button clicks mark article as read

### ISSUE THREAD

**Issue by rnovacek** [owncloud/news#884]
When I open browser context menu (right click) when the mouse pointer is on some article in the feed, that item gets marked as read. I don't think this is correct behaviour. The same happens when the middle mouse button is pressed on the article body (not on clickable header).

I suppose that there should be some filter in the click (mousedown) event handler that should check if the clicked button is left mouse button.

Owncloud 8.2
News 085f27a (current master)
Firefox 41.0.2 on Fedora 22

**Comment by BernhardPosselt** [comment]
Middle click is definitely correct because you usually use it to open links in the article. 

As for right click: When do you really right click an article? Only thing I can think of is selecting text. In order to do this however you have to use a left click for selecting the content.

Non issue from my POV

@cosenal @IBBoard opinions?

**Comment by cosenal** [comment]
I have not been bothered by the mouse-click actions so far, but I don't have a strong opinion either way. I am sure @jancborchardt knows better

**Comment by rnovacek** [comment]
I don't think middle click is correct. If I middle click the header, then it opens the article and marks it as read. That's correct. But when I middle click on the article body, it doesn't open the article and just marks it as read.

For the right click, apart from opening context menu, it also marks the article as read when I use mouse gesture (using FireGestures Firefox addon) - I use right click and mouse wheel to switch between tabs and when I release the right button on the article, it's marked as read without me noticing that it happened.

**Comment by IBBoard** [comment]
I use compact view, so my articles get marked as read when I open them and I don't have these issues.

I can see some standard corner-cases where marking as read would be wrong (e.g. right-click > Inspect Element or Save Page As or View Source) but I don't know if there's enough fidelity in the events to differentiate "Right-click > Open Link In New Tab" from "Right-click > View Source". The only option might be to complicate the right-click and only mark as read right right-clicking a link in the article body, rather than anywhere in the article body, but then that wouldn't mark as read if you saved an image...

As for middle-click, I only know of it being used to open links in new tabs (at which point you're clicking a link in the article anyway, so marking as read seems reasonable) or to send a window into the background (at which point you're interacting with the browser window, not the page). What @rnovacek said sounds like accidental middle-clicks in the body. Again, all we could do is filter the clicking to "did the user intend it - guess by seeing if it happened on a link", but then will someone argue that they're having the same issue with accidentally left-clicking articles and it marking it as read before they really meant it, and wouldn't we better if we had a "mark as read" button instead?

**Comment by BernhardPosselt** [comment]
From what I've understood so far I think OP's problem is his mouse gesture addon. The only "fix" I can see is to not react on right click but there's still the issue with middle clicks which can not be resolved.

This needs to be addressed in the browser addon IMHO since this will also affect other pages: The addon should not let the event bubble up if it was recognized as a gesture.
