### ISSUE TITLE
News icon looks like "left justify" in a word processor

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/news#889]
The news app is fantastic, however its icon is forgetable, and worse, easily mistaken for the commonly used "left justify" icon in just about every word processor / text editor.

Rather than just sit and complain, I thought I'd come up with a proposal for something that communicates what it does better, that is, marrying reading RSS feeds in ownCloud. Here's my suggestion:

250px version:
![ownews-250px](https://cloud.githubusercontent.com/assets/401733/11165715/65bfbb9a-8ae5-11e5-9b8a-4b12e75825a1.png)

32px version:
![own-news](https://cloud.githubusercontent.com/assets/401733/11165716/6d6b6b00-8ae5-11e5-97f8-fec2f21ba9b3.png)

Note: This is currently just a draft to get feedback on the overall concept. If the concept is decent, there are a bunch of things that I'd subtly improve. Inkscape SVG available on request.

**Comment by BernhardPosselt** [comment]
Looks awesome, good point :)

However I wonder if we should just use the RSS symbol (without the cloud), just a random thought.

What do you think @IBBoard @cwmke @kgraefe @ogasser @vgezer @cosenal @MorrisJobke @LukasReschke

**Comment by IBBoard** [comment]
The cloud and RSS bands looks good, but I think RSS symbol on its own would be more obvious and direct.

**Comment by cosenal** [comment]
Sorry, I don't like it, there is no point in showing a cloud icon when you're already inside the owncloud view. Back in the days, when we created the app, we discarded the RSS symbol, because it could have been mistaken with some app that produces feeds (like the Activity app). 
Honestly, I don't see anything wrong with the actual icon. cc @jancborchardt

**Comment by IBBoard** [comment]
Sorry, but I disagree. Photo icon looks like a photo, Contacts looks like people, bookmarks is the common "favourite" star, Files is a folder, Calendar is a calendar and Tasks is a tick for a task list. They all represent themselves. News icon is basically how it is described in the issue.

Having something more related to feeds and less like a list of text/justified text would be good.

Are there any RSS app icons to take inspiration from?

**Comment by Bugsbane** [comment]
> I wonder if we should just use the RSS symbol

I think this could work, too. Either one would work better than the current icon imo, as it's easily confused for something else, and doesn't clearly indicate news / rss.

**Comment by BernhardPosselt** [comment]
Some sort of news paper symbol probably?

**Comment by Bugsbane** [comment]
> no point in showing a cloud icon when you're already inside the owncloud view

A fair point.

> Some sort of news paper symbol probably?

That could be done. Is there any reason to not just use the RSS symbol by itself? This seems like probably the simplest solution. Otherwise, possibly a newspaper with the RSS icon on it?

**Comment by Bugsbane** [comment]
Just for comparison, I did a mockup of a newspaper+RSS icon and a mockup of a straight rss icon:

![news-paper](https://cloud.githubusercontent.com/assets/401733/11166394/9fb9ff9e-8aff-11e5-9242-a0bf6f4feecc.png)

![news-rss](https://cloud.githubusercontent.com/assets/401733/11166395/aa812bb4-8aff-11e5-8df2-ae077911d752.png)

Personally, I prefer the second, as it's visually simpler and more (pardon the pun) iconic.

**Comment by jancborchardt** [comment]
I agree with @cosenal in that there’s no issue with the current logo. Using a cloud symbol is not needed when you are in the view. The RSS reader symbol is not known by many and looks more like a tilted wifi symbol and could easily be misunderstood.

@Bugsbane @BernhardPosselt a specific newspaper image is too complex for an icon. They need to have very simple shapes to be quickly distinguishable. Basically the current icon is a simplified version of a newspaper, so I don’t see a problem.

> Sorry, but I disagree. Photo icon looks like a photo, Contacts looks like people, bookmarks is the common "favourite" star, Files is a folder, Calendar is a calendar and Tasks is a tick for a task list. They all represent themselves. News icon is basically how it is described in the issue.
>
> Having something more related to feeds and less like a list of text/justified text would be good.

@IBBoard this is exactly the reason why the News app icon looks like it does today. It looks like text, what you actually see in the app. Same for the other apps as you describe.

**Comment by cwmke** [comment]
Personally, I agree with @jancborchardt that the current symbol looks fine.  If I had a choice between that and @Bugsbane's RSS design, I would choose the RSS logo though.

The fact that some people won't recognize it is a fair point, but it is in their best interest to learn since it is occasionally the only indication of a website's feed (annoyingly).

**Comment by jancborchardt** [comment]
@cwmke since people can just paste the address of the website in the app and the feed will be autodetected, forcing people to learn the RSS sign is not really necessary.

**Comment by cosenal** [comment]
And for that we should have a browser plugin that detects the feed.

**Comment by IBBoard** [comment]
Forcing people to learn the RSS sign when it isn't popular/common would be bad, but lots of places already use it.

Even IE and Firefox uses the RSS icon (http://learnwebtutorials.com/subscribe-rss-feeds-firefox-internet-explorer-browser step 4 and http://tarltonguides.law.utexas.edu/content.php?pid=136848&sid=1185328). I'm fairly sure BBC News uses the RSS icon (although I don't want to check at the moment because I'm trying to avoid sports results!) as do a large number of blogs.

Search "[feed icon](https://www.google.co.uk/search?q=feed+icon&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIzcCv1JGTyQIVQjgUCh0MEQCG&biw=1024&bih=942) and you almost universally get the RSS symbol or a variation thereof. Searching "[Subscribe to feed](https://www.google.co.uk/search?q=feed+burner+button&biw=1024&bih=942&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIlJfEgJCTyQIVylUaCh22vAyi#tbm=isch&q=subscribe+to+feed)" gets the same. Even if you want to ditch "feed" as too technical then "[subscribe to news](https://www.google.co.uk/search?q=feed+burner+button&biw=1024&bih=942&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIlJfEgJCTyQIVylUaCh22vAyi#tbm=isch&q=subscribe+to+news)" turns up a mix of RSS feed icons and email icons (because of the "subscribe to email newsletter" interpretation of that phrase, which isn't relevant here). I'm not saying that the RSS icon is perfect, but it has more in common with a news feed app than a list/left-.aligned text

I agree that a newspaper won't work, because there's no trivial way to iconify a newspaper. Anything that you do to iconify a newspaper will probably end up being confusing with a Documents plugin. What we have now is only discernible as News because it was the one that appeared after I enabled News and everything else obviously isn't News. The only reason I don't confuse it with my To Do list is because a tick is more strongly associated with a to do list than a list of unidentified lines is.

Given that people using news feeds are already more technical than the norm, is it not reasonable to assume that they're at least vaguely familiar with the RSS icon?

Also, is no-one going to mention how the default favicon in the news feed appears to be the RSS icon? ;)

**Comment by Bugsbane** [comment]
> Given that people using news feeds are already more technical than the norm, is it not reasonable to assume that they're at least vaguely familiar with the RSS icon?

I would say so. In fact I'd go further and say that if they're like to use an RSS reader, that they're likely to know what the RSS icon stands for already.

**Comment by BernhardPosselt** [comment]
Some reference art:

* Feedly: looks like a modified RSS icon

 ![](http://s3.feedly.com/img/feedly-full-black.png)

* TT-RSS: looks like an RSS icon

![](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tt-rss-icon.png)

* Liferea: Newspaper
![](http://2.bp.blogspot.com/-fLXwfCkJHoM/UvLqz0TarZI/AAAAAAAAA6w/fe15dMF3mro/s1600/Liferea.png)

* Akkregator: RSS icon
![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Akregator.svg/128px-Akregator.svg.png)
 
* FeedReader: RSS icon
![](https://upload.wikimedia.org/wikipedia/en/4/49/Feedreader_png.png)

* NewsBlur: A sun in RSS colors combined with atom icon 
![](https://upload.wikimedia.org/wikipedia/en/b/be/NewsBlur_logo.png)

* Pulse: Basically a retake on the atom feed icon
![](https://upload.wikimedia.org/wikipedia/en/7/76/Logo_for_Pulse_Software.jpg)

The Old Reader and digg Reader have custom icons

**Comment by cosenal** [comment]
The reason I never liked to use the rss/atom icon for our app is that in my opinion that should be reserved for _producers_ of feeds, rather than _digester_. And the ownCloud menu is one of those places where that could actually be confusing.
Except the Feedly one, all those icons are damn ugly :)
For the sake of memory and nostalgia, let me show you guys the very first ownCloud News logo (stolen by Lilina on which I though the app was going to be based): http://getlilina.org/shared/images/logos/logo.png

**Comment by jancborchardt** [comment]
> Feedly: looks like a modified RSS icon

@BernhardPosselt it’s a stylized F mixed with a list for reading. It’s as close as it gets to our icon …
All the other ones are apps used by very few people and don’t really serve as reference art. Except maybe Newsblur and Pulse, and they are based on circles with no reference to the Atom icon, as you retcon into them. ;)

> Given that people using news feeds are already more technical than the norm, is it not reasonable to assume that they're at least vaguely familiar with the RSS icon?

@IBBoard we’re not producing software for technical people or to serve to the status quo. The News app is aimed to be easy to use as to be useful for less technical people as well. Just as apps like Pocket, and the probably upcoming Facebook reader do.

**Comment by Bugsbane** [comment]
Agreed. Seems to me that anyone who installs this is doing so because they know what an RSS feed is and want to read them. If they know what an RSS feed is, then the simplest, most recognizable icon for them - technical or not - is the RSS icon. Personally I am not a developer, coder or anything like that, and the RSS icon is what I would expect to see.

As to the RSS icon only being for producers, would we really get rid of the envelope icon for the mail app because it should only be for people sending email, not for an email reading app? Or save the folder icon for people creating files, and not allow it for people browsing them as we do now? Or save the photo icon for photography apps and ban it's use from any photo viewing app (such as Gallery)? RSS like email is intended to be a channel to get information from a sender to a recipient. It is the medium of exchange between two parties, and thus to me it makes sense for it to represent both a producer with a feed to share, and an app that reads those feeds.

**Comment by BernhardPosselt** [comment]
Any conclusion on this :D

**Comment by jancborchardt** [comment]
I stand by my previous comments, and I’d prefer we close this.

**Comment by BernhardPosselt** [comment]
Closing then :)

**Comment by IBBoard** [comment]
Yeah, I think the conclusion was that most users think the current icon looks too generic and not specifically news/RSS related, but that an earlier decision was made that the RSS icon wouldn't be used (because of some distinction between "publishing RSS" and "reading RSS").

I'd rather the icon was improved, but I'm not going to lose sleep over it staying the same (TBH I only access OwnCloud for News/RSS, and then my email clients sync to calendar and address book, but I never use them directly, so I don't often see the icon).
