### ISSUE TITLE
Requirement of PHP 5.6 is too strict

### ISSUE THREAD

**Issue by paroj** [owncloud/news#970]
Ubuntu 14.04 will be still supported until 2019 and Ubuntu 16.04 is not out yet. Even if it was, nobody sane would upgrade the server immediately.
Therefore the bump to PHP5.6 is premature. I also doubt that there are any PHP5.6 features that are deliberately needed.

Furthermore Travis gives you 14.04 images, so you can easily ensure that PHP5.5 Ubuntu 14.04 still works.

**Comment by BernhardPosselt** [comment]
See https://github.com/owncloud/news/issues/968

**Comment by BernhardPosselt** [comment]
For a better understanding:
* There are various functions that are already using PHP 5.6 features which required backporting to 5.5 before (multibyte string curl functions for instance)
* Various libraries such as the latest PHPUnit already require 5.6
* Security support for 5.5 will run out in 2 months http://php.net/supported-versions.php

Apart from that I wanted to drop a lot of things at once (e.g. 9.0 requirement, database version requirements) so that frequent dependency changes will happen less often. I think dealing with new version requirements once a year is probably easier to maintain and plan for than every 3 months.

Onte thing to keep in mind is that I don't have a lot of time to maintain the app since I've got a job and a family. Would you rather see bugfixes and new features or longer support time frames :)?

PS: If you are interested in providing long term support for the app (backporting bug and security fixes) please let me know. I'm sure we can work out a workflow :)

**Comment by paroj** [comment]
> Security support for 5.5 will run out in 2 months

this is not really a problem as ubuntu will backport security fixes.

However I understand that the time you can invest is limited and supporting a configuration than what you personally run is an overhead.

The main issue with PHP5.6 for me is that I run Ubuntu on an Odroid U3, which will probably not get an update to 16.04 anytime soon.

However I found out that the PHP5.6 PPA also provides ARM builds. I will give that one a try - if it does not work out I will take a look on how much effort the backporting would be.

**Comment by BernhardPosselt** [comment]
I wouldn't be so sure that security backports will be handled in a timely manner. First of all Ubuntu is a desktop and not a server distro, second no major other long term stable distro ships php 5.5 (rhel 5.4, Debian 5.6). Third I've reported a security bug where a fix exists already in the 5.5 branch 6 months ago https://bugs.launchpad.net/ubuntu/trusty/+source/php5/+bug/1509817

It's still not fixed https://launchpad.net/ubuntu/trusty/+source/php5/+changelog

If they can't even backport security fixes in the 5.5 branch, how should this work for newer ones :P

**Comment by paroj** [comment]
I see so the PPA is probably the better choice as it is done by the Debian PHP maintainer.

I skipped PHP 5.6 and went directly for PHP7 using the PPA, which gave a noticable performance boost.
The only minor issue I had was with APCu which needs to be switched from `php5-apcu` to `php-apcu` - otherwise Owncloud does not start.

**Comment by BernhardPosselt** [comment]
Great to see that it worked out :)

**Comment by abranson** [comment]
If anyone comes across this, I don't recommend going for the PHP7 PPA - it seems to be a bit bleeding edge. In my case, I had to patch owncloud to stop a login loop, and then found that Roundcube hasn't released a PHP7 compatible version yet.. Use the PHP5.6 PPA instead, which seems to work fine.

**Comment by paroj** [comment]
the breaking change was in PHP7 - so this was not specific to the PPA
https://github.com/owncloud/core/pull/24326
