### ISSUE TITLE
Email for new items in feeds

### ISSUE THREAD

**Issue by florianaudon** [owncloud/news#983]
Hello,

Is it possible to receive an emails for each new articles in feeds or  have on email per day to resume all articles of the day?

Best Regards,

**Comment by BernhardPosselt** [comment]
Why do you want constant email spam if you can just open the web interface?

**Comment by florianaudon** [comment]
Sometimes I haven't a computer to access to this interface and the application on android doesn't work on my smartphone. But in this case, I can receive notification for new mail.

**Comment by BernhardPosselt** [comment]
There are two free android apps, did you check them out?

**Comment by BernhardPosselt** [comment]
This app also works on mobile Firefox and chrome btw

**Comment by florianaudon** [comment]
I've already test these two appsb on android).
The first app, It can sychronize only one time. After nothing happen.
The second app, there are a minor bug, there is a button, which isn't always display. When I use the scroll, the button disappear.

**Comment by BernhardPosselt** [comment]
I'd suggest that you file a bug then ;)

Personally I'm using this one which is incredibly well done https://play.google.com/store/apps/details?id=de.luhmer.owncloudnewsreader&hl=de

**Comment by BernhardPosselt** [comment]
Closing this because this feature request is a bug in disguise. Rather than working around the bug, let's fix it in the mobile apps ;)

Apart from that, moving to an email based solution is not a goal since E-Mail is a format where today you are flooded with messages. It's already hard to keep up with the daily mail traffic.

If absolutely necessary, one can use one of the many solutions that send rss updates via mail, see https://www.google.at/#q=email+feeds&gws_rd=cr or simply write a serverside plugin see https://github.com/owncloud/news/wiki/How-to-write-Plugins
