### ISSUE TITLE
Feature: Ability to view read articles on a feed

### ISSUE THREAD

**Issue by koehn** [owncloud/news#995]
Feature request, not an issue:

When Reading a feed/folder/unread articles, if the page refreshes (as happens a lot on mobile devices), there's no easy way to get back to the article you were reading prior to the refresh. It would be nice to have a "Show recently read articles" function that a user could activate to show articles no longer available. 

To achieve this today the user must click on the settings button, click "Show all articles", click the settings button again, and start scrolling. Reducing the clicks would make the tool much more pleasant to use.

**Comment by BernhardPosselt** [comment]
What do you mean the page refreshes :)

There is no auto refresh

**Comment by BernhardPosselt** [comment]
My stance on that request is the following:

It should not be that you can easily refresh the page. The only way I know if of is either by refreshing using a keyboard shortcut (f5, r, not relevant on mobile), clicking on the feed name if in folder mode or by clicking on another feed which is hard on mobile because the sidebar is hidden. The reload button at the top has been removed and will be gone in the next release.

There should not be an automatic refresh and therefore the chance of an accidental refresh is very low. This makes the show all articles option a good enough option and IMHO this feature is not required. Closing hence

**Comment by koehn** [comment]
The page refresh happens primarily when:

1. Waking a desktop computer from sleep (e.g., Firefox on MacOS)
2. Switching to a News page in a browser on a tablet after it's been offline for a while (e.g., Safari on iOS)

In both of these cases the result is a full page refresh resulting in the loss of place (the same page is opened, but read articles aren't displayed).

**Comment by BernhardPosselt** [comment]
This a core issue then. Simply putting your template to sleep should not lose the connection. Please reopen there ;)
